# 설정파일.........................................
# properties 파일
# 1. 톰캣 포트번호
# 2. View 기본위치 설정. 
# 3. 읽을 파일. 
#server.port = 8081 
#spring.mvc.view.prefix = /WEB-INF/Views/
#spring.mvc.view.suffix = '.jsp'
#spring.application.name=monkey


# yaml파일. 
server:
  port : 8082

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: '.jsp'
  application:
    name: Eureka02

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.0.70:8761/eureka/
    registryFetchIntervalSeconds: 5
  